---
name: {{project_name}}
services:
  app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{project_name}}.rule=Host(`{{project_name}}.jorpo.loco`)"
      - "traefik.http.routers.{{project_name}}.entrypoints=web"
      - "traefik.http.services.{{project_name}}.loadbalancer.server.port={{port}}"
      - "traefik.docker.network=loco"
    networks:
      - loco

networks:
  loco:
    external: true
