http:
  routers:
    {{cluster_name}}:
      rule: "HostRegexp(`{subdomain:.+}.{{cluster_name}}.jorpo.loco`) || Host(`{{cluster_name}}.jorpo.loco`)"
      entryPoints: ["web"]
      service: {{cluster_name}}
    {{cluster_name}}-secure:
      rule: "HostRegexp(`{subdomain:.+}.{{cluster_name}}.jorpo.loco`) || Host(`{{cluster_name}}.jorpo.loco`)"
      entryPoints: ["websecure"]
      service: {{cluster_name}}
      tls: {}

  services:
    {{cluster_name}}:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:{{http_port}}"